name: Deploy Rick and Morty API

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2

    # Set up Python for our application
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    # Install dependencies for testing
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests pytest

    # Start Minikube
    - name: Start Minikube
      id: minikube
      run: |
        curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
        sudo install minikube-linux-amd64 /usr/local/bin/minikube
        minikube start --driver=docker

    # Install Helm
    - name: Install Helm
      run: |
        curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash

    # Build and load the Docker image into Minikube
    - name: Build and Load Docker Image
      run: |
        eval $(minikube -p minikube docker-env)
        docker build -t rickmorty-api:latest .
        echo "Verifying image is built:"
        docker images | grep rickmorty-api
        echo "Loading image into minikube:"
        minikube image load rickmorty-api:latest
        echo "Verifying image in minikube:"
        minikube ssh 'docker images | grep rickmorty-api'

    # Deploy using Helm
    - name: Deploy with Helm
      run: |
        helm install my-rickmorty ./helm/rickmorty
        echo "Checking initial deployment status..."
        kubectl get deployments
        kubectl get pods -o wide
        echo "Detailed pod information:"
        kubectl describe pods

    # Wait for deployment to be ready
    - name: Wait for deployment
      run: |
        echo "Checking minikube status and available images:"
        minikube status
        minikube ssh 'docker images' # Shows what images are actually available in minikube
        
        echo "\nCurrent deployment status before waiting:"
        kubectl get deployments
        kubectl get pods
        
        echo "\nChecking namespace events (this shows chronological cluster activity):"
        kubectl get events --sort-by='.metadata.creationTimestamp'
        
        echo "\nStarting wait for deployment..."
        kubectl wait --for=condition=available --timeout=300s deployment/my-rickmorty &
        WAIT_PID=$!
        
        # While we're waiting, check pod status every 30 seconds
        for i in {1..30}; do
          echo "\nChecking pod status (attempt $i):"
          kubectl get pods
          kubectl describe pods
          
          # Try to get logs from pods if they exist
          echo "\nPod logs (if available):"
          for pod in $(kubectl get pods -o name); do
            echo "Logs from $pod:"
            kubectl logs $pod --all-containers --prefix || echo "No logs available yet"
          done
          
          # Check if the wait command is still running
          if ! kill -0 $WAIT_PID 2>/dev/null; then
            break
          fi
          
          sleep 30
        done
        
        # Wait for the original wait command to finish
        wait $WAIT_PID || true
        
        echo "\nFinal deployment status:"
        kubectl get deployments -o wide
        kubectl get pods -o wide
        kubectl describe pods
        
        echo "\nFinal namespace events:"
        kubectl get events --sort-by='.metadata.creationTimestamp'

    # Port forward in background for testing
    - name: Setup port forward
      run: |
        kubectl port-forward service/my-rickmorty 8080:80 &
        sleep 5  # Give it a moment to establish the connection

    # Run tests against the deployment
    - name: Test Deployment
      run: |
        # Test health check endpoint
        HEALTH_STATUS=$(curl -s http://localhost:8080/healthcheck | jq -r '.status')
        if [ "$HEALTH_STATUS" != "healthy" ]; then
          echo "Health check failed"
          exit 1
        fi
        
        # Test characters endpoint
        CHARS_STATUS=$(curl -s http://localhost:8080/characters | jq -r '.status')
        if [ "$CHARS_STATUS" != "success" ]; then
          echo "Characters endpoint failed"
          exit 1
        fi
        
        # Test CSV endpoint
        CSV_RESPONSE=$(curl -s -I http://localhost:8080/characters/csv)
        if ! echo "$CSV_RESPONSE" | grep -q "text/csv"; then
          echo "CSV endpoint failed"
          exit 1
        fi

    # Cleanup
    - name: Cleanup
      if: always()
      run: |
        helm uninstall my-rickmorty || true
        minikube delete